name: schedule

on:
  schedule:
    # 真实 -8
    - cron: "30 3 * * *"

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - name: eating eating
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"msg_type":"text","content":{"text":"点饭啦"}}' ${{secrets.GROUP_URL}}