name: schedule

on:
  schedule:
    - cron: "20 14 * * *"

jobs:
  bot:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
      - name: eating eating
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"msg_type":"text","content":{"text":"点饭啦"}}' ${{secrets.GROUP_URL}}